version: '2'
networks:
  extnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.251.251.0/24
        gateway: 172.251.251.1
  lan:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.250.250.0/24
        gateway: 172.250.250.1
        
services:
 apache:
    image: bitnami/apache:2.4.54
    restart: always
    networks:
      extnetwork:
        ipv4_address: 172.251.251.251
    ports:
      - "9091:8080"
    volumes:
      - ./apache/index.html:/opt/bitnami/apache2/htdocs/index.html
      - ./apache/my_vhost.conf:/vhosts/my_vhost.conf
      
 SSRF:
    image: php:7.0.8-apache
    volumes:
      - ./SSRF:/var/www/html
    restart: always
    networks:
      extnetwork:
        ipv4_address: 172.251.251.2
      lan:
        ipv4_address: 172.250.250.2

 CodeExec:
    image: php:7.0.8-apache
    volumes:
      - ./CodeExec:/var/www/html
    restart: always
    networks:
      lan:
        ipv4_address: 172.250.250.4
 
 CommandExec:
    image: php:7.0.8-apache
    volumes:
      - ./CommandExec:/var/www/html
    restart: always
    networks:
      lan:
        ipv4_address: 172.250.250.5
    
 XXE:
    image: php:7.0.8-apache
    volumes:
      - ./XXE:/var/www/html/
    restart: always
    networks:
      lan:
        ipv4_address: 172.250.250.6
 tomcat:
    build: ./Tomcat
    restart: always
    networks:
      lan:
        ipv4_address: 172.250.250.7
 
 mysql:
    image: mysql:5.6
    environment:        
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./MySQL/flag:/flag
      - ./MySQL/flag.sql:/docker-entrypoint-initdb.d/flag.sql
      - ./MySQL/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - ./MySQL/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    restart: always
    expose:
      - "3306"
    networks:
      lan:
        ipv4_address: 172.250.250.8

 redisunauth:
    build: ./Redisunauth
    restart: always
    networks:
      lan:
        ipv4_address: 172.250.250.9
 
 redisauth:
    build: ./Redisauth
    restart: always
    networks:
      lan:
        ipv4_address: 172.250.250.10
 
 sqli:
   image: acgpiano/sqli-labs
   restart: always
   networks:
     lan:
       ipv4_address: 172.250.250.11
 
 fastcgi:
   image: nginx:1
   volumes:
    - ./Fastcgi/www:/usr/share/nginx/html
    - ./Fastcgi/default.conf:/etc/nginx/conf.d/default.conf
   depends_on:
    - php
   restart: always  
   networks:
     lan:
       ipv4_address: 172.250.250.12

 php:
   image: php:7.2.10-fpm
   volumes:
    - ./Fastcgi/www:/var/www/html
   restart: always  
   networks:
     lan:
       ipv4_address: 172.250.250.13

 mysql_ssrf:
   image: php:7.2.10-apache
   volumes:
     - ./mysql_ssrf/www:/var/www/html
   restart: always
   networks:
     extnetwork:
       ipv4_address: 172.251.251.3
     lan:
       ipv4_address: 172.250.250.3